name: Kenneth Hung
department: Department of Mathematics
university: UC Berkeley
keywords: Kenneth, Hung, Berkeley, math, mathematics, stat, statistics
url: http://kenhung.me
email: kenhung@berkeley.edu
markdown: rdiscount
office: 787 Evans Hall